FROM python:3.11-slim

WORKDIR /app

# Copy train requirements and install
COPY train/requirements.txt requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy train code
COPY train/ train/
# Copy db helper
COPY db/ db/

# Ensure models folder exists
RUN mkdir -p /app/models

ENV PYTHONPATH=/app

CMD ["python", "train/main.py"]